<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == '' Or '$(Configuration)' == 'Debug'">
    <EnvironmentName>Development</EnvironmentName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' != '' AND '$(Configuration)' != 'Debug' ">
    <EnvironmentName>Production</EnvironmentName>
  </PropertyGroup>


  
  <ItemGroup>
    <ProjectReference Include="..\MalakaBooks.ConfigSetting\MalakaBooks.ConfigSetting.csproj" />
    <ProjectReference Include="..\MalakaBooks.DataValidator\MalakaBooks.DataValidator.csproj" />
    <ProjectReference Include="..\MalakaBooks.Entity\MalakaBooks.Entity.csproj" />
    <ProjectReference Include="..\MalakaBooks.IS4RegistrationService\MalakaBooks.IS4RegistrationService.csproj" />
    <ProjectReference Include="..\MalakaBooks.ViewModel\MalakaBooks.ViewModel.csproj" />
    <ProjectReference Include="..\MalakaBooks.IRepository\MalakaBooks.IRepository.csproj" />
    <ProjectReference Include="..\MalakaBooks.Repository\MalakaBooks.Repository.csproj" />
    <ProjectReference Include="..\MalakaBooks.Mediator\MalakaBooks.Mediator.csproj" />
    <ProjectReference Include="..\MalakaBooks.Validator\MalakaBooks.Validator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Subur.Security.AuthProvider" />
    <PackageReference Include="Subur.API.SwaggerProvider" />
    <PackageReference Include="Subur.API.VersioningProvider" />
    <PackageReference Include="Subur.Messaging.MediatRProvider" />
    <PackageReference Include="Subur.Extension" />
    <PackageReference Include="Subur.Security.CorsConfig" />
    <PackageReference Include="Subur.Security.CorsProvider" />
    <PackageReference Include="Subur.Storage.CacheProvider" />
    <PackageReference Include="Subur.Storage.MongoDbProvider" />

    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="IdempotentAPI" />
    <PackageReference Include="IdempotentAPI.Cache.DistributedCache" />
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
</Project>
