<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\MardikaPortfolio\API\Mardika.Simasrim.Service\Mardika.Simasrim.Service.csproj" />
    <ProjectReference Include="..\MalakaBooks.ConfigSetting\MalakaBooks.ConfigSetting.csproj" />
    <ProjectReference Include="..\MalakaBooks.Entity\MalakaBooks.Entity.csproj" />
    <ProjectReference Include="..\MalakaBooks.IDataValidator\MalakaBooks.IDataValidator.csproj" />
    <ProjectReference Include="..\MalakaBooks.IRepository\MalakaBooks.IRepository.csproj" />
    <ProjectReference Include="..\MalakaBooks.IS4RegistrationService\MalakaBooks.IS4RegistrationService.csproj" />
    <ProjectReference Include="..\MalakaBooks.ViewModel\MalakaBooks.ViewModel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="libphonenumber-csharp" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
