<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\MardikaPortfolio\API\Mardika.Simasrim.Service\Mardika.Simasrim.Service.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Skoruba.IdentityServer4.Admin.BusinessLogic.Identity" />
  </ItemGroup>
</Project>
