<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MalakaBooks.Entity\MalakaBooks.Entity.csproj" />
    <ProjectReference Include="..\MalakaBooks.IDataValidator\MalakaBooks.IDataValidator.csproj" />
    <ProjectReference Include="..\MalakaBooks.Repository\MalakaBooks.Repository.csproj" />
  </ItemGroup>

</Project>
